version: 2
jobs:
  test:
    working_directory: ~/itk_common
    environment:
      - MIX_ENV: test
    docker:
      - image: circleci/elixir:1.8
      - image: rabbitmq:3.7
      - image: redis:latest
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test

  formatting:
    working_directory: ~/itk_common
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix credo --all --strict

  dialyzer:
    working_directory: ~/itk_common
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix dialyzer --halt-exit-status

workflows:
  version: 2
  build-deploy:
    jobs:
      - formatting:
          filters:
            branches:
              ignore: master
      - test:
          filters:
            branches:
              ignore: master
      - dialyzer:
          filters:
            branches:
              ignore: master

notify:
  webhooks:
    - url: https://itk-webhook.ucoachapp.com/circle
